"""add admin_events and posts

Revision ID: 1acb9548750a
Revises: merge_all_heads_20251207
Create Date: 2025-12-16 00:53:56.516479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1acb9548750a'
down_revision = 'merge_all_heads_20251207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('zone', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('homepage_banners', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # NOTE: Skipping loyalty_points index modifications to avoid MySQL FK issues

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_top_pick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('is_new_arrival_featured',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_new_arrival_featured',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('is_top_pick',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # NOTE: No reverse op for loyalty_points index since we did not modify it

    with op.batch_alter_table('homepage_banners', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=mysql.INTEGER(),
               nullable=False)

    op.drop_table('posts')
    op.drop_table('admin_events')
    # ### end Alembic commands ###
