"""delivery_zones_coupons_and_fields

Revision ID: 1f0049d48e3d
Revises: c387886e5610
Create Date: 2025-11-14 02:25:46.410382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0049d48e3d'
down_revision = 'c387886e5610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if not insp.has_table('delivery_zones'):
        op.create_table('delivery_zones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('eta', sa.String(length=120), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_zone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coupon_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key('fk_orders_delivery_zone_id_delivery_zones', 'delivery_zones', ['delivery_zone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_delivery_zone_id_delivery_zones', type_='foreignkey')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('coupon_code')
        batch_op.drop_column('delivery_zone_id')

    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
