"""review photos, category hero images, review moderation

Revision ID: 67e8364dc266
Revises: e1b2c3d4
Create Date: 2025-11-27 00:06:01.288423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e8364dc266'
down_revision = 'e1b2c3d4'
branch_labels = None
depends_on = None


def upgrade():
    # Idempotent creation using inspector
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())

    if 'category_hero_images' not in tables:
        op.create_table('category_hero_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('image_url', sa.String(length=500), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('starts_at', sa.DateTime(), nullable=True),
        sa.Column('ends_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'review_photos' not in tables:
        op.create_table('review_photos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('review_id', sa.Integer(), nullable=False),
        sa.Column('image_url', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # Skip dropping indexes on loyalty_points to avoid FK constraint issues on MySQL
    # If needed in the future, handle with inspector and safe checks.

    # Add reviews.is_approved if missing
    cols = {c['name'] for c in inspector.get_columns('reviews')}
    if 'is_approved' not in cols:
        with op.batch_alter_table('reviews', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('loyalty_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    op.drop_table('review_photos')
    op.drop_table('category_hero_images')
    # ### end Alembic commands ###
