"""Add loyalty_points.points and last_updated columns

Revision ID: aa23716e80c7
Revises: b1247ead3268
Create Date: 2025-11-25 14:32:45.598366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa23716e80c7'
down_revision = 'b1247ead3268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # On some backends (e.g., MySQL) the temporary table may not exist; guard the drop
    from sqlalchemy import inspect, text
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())
    if '_alembic_tmp_loyalty_points' in tables:
        op.drop_table('_alembic_tmp_loyalty_points')
    # Gather existing columns to avoid duplicate/add/drop errors across backends
    cols = {c['name'] for c in inspector.get_columns('loyalty_points')}
    with op.batch_alter_table('loyalty_points', schema=None) as batch_op:
        if 'points' not in cols:
            batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        if 'last_updated' not in cols:
            batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        if 'total_earned' in cols:
            batch_op.drop_column('total_earned')
        if 'points_balance' in cols:
            batch_op.drop_column('points_balance')
        if 'total_redeemed' in cols:
            batch_op.drop_column('total_redeemed')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_rider_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_rider_id', 'riders', ['rider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_rider_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_rider_id', 'riders', ['rider_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('loyalty_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_redeemed', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('points_balance', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_earned', sa.INTEGER(), nullable=True))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('points')

    op.create_table('_alembic_tmp_loyalty_points',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
